function getData(){
	var dataAMZ = {
	B00CH9QWOU: {US: "https://amzn.to/32iuHZ4",CA: "https://amzn.to/3gprFH2",UK: ""},
	B01G6Q45AM: {US: "https://amzn.to/313UUKs",CA: "https://amzn.to/2NjGBZT",UK: ""},
	B07JH7GS76: {US: "https://amzn.to/307WQzt",CA: "https://amzn.to/2AfqjOG",UK: ""},
	B07MRG5F4J: {US: "https://amzn.to/2Oo5rbJ",CA: "https://amzn.to/3dSerAj",UK: ""},
	B07KXPXN5T: {US: "https://amzn.to/3eFtWvA",CA: "https://amzn.to/3eDGpQD",UK: ""},
	B01F6XZ6BS: {US: "https://amzn.to/2C0CtfC",CA: "https://amzn.to/2YKwBzo",UK: ""},
	B07FZ8S74R: {US: "https://amzn.to/2Zs3em3",CA: "",UK: ""},
	B07VR22832: {US: "https://amzn.to/3eCeJeT",CA: "",UK: ""},
	B00UWP07LK: {US: "https://amzn.to/3gXsYwf",CA: "https://amzn.to/3eVX7ej",UK: ""},
	B08232VZBR: {US: "https://amzn.to/3jcbPRE",CA: "https://amzn.to/2Ao39WM",UK: ""},
	B01ALBMIEI: {US: "https://amzn.to/3iZx5tD",CA: "https://amzn.to/2BnGDxf",UK: ""},
	B083Q2L4VZ: {US: "https://amzn.to/2WiaSNw",CA: "https://amzn.to/2Z1OI2Z",UK: ""},
	B078YZ586K: {US: "https://amzn.to/2AXEQPH",CA: "https://amzn.to/2UdefEG",UK: ""},
	B07RCNHTLS: {US: "https://amzn.to/2ZpyMZI",CA: "https://amzn.to/36LR7lD",UK: ""},
	B07VM1HQ87: {US: "https://amzn.to/306oVqI",CA: "https://amzn.to/2CwauEg",UK: ""},
	B000058TJ3: {US: "https://amzn.to/30bMI8y",CA: "https://amzn.to/3114bCV",UK: ""},
	B07VVK39F7: {US: "https://amzn.to/3erT890",CA: "https://amzn.to/2U7sWcn",UK: ""},
	B01D3FOD0Q: {US: "https://amzn.to/3hws8qR",CA: "",UK: ""},
	B07MY2H45K: {US: "https://amzn.to/3gQeUEW",CA: "https://amzn.to/3cvgnxN",UK: ""},
	B00474X5DO: {US: "https://amzn.to/33hSsB9",CA: "",UK: ""},
	B07FDFP79J: {US: "https://amzn.to/3j21BDf",CA: "https://amzn.to/30jFwJv",UK: ""},
	B07HB7QBQ2: {US: "https://amzn.to/32fTRYg",CA: "https://amzn.to/3erCIhE ",UK: ""},
	B08375XS5G: {US: "https://amzn.to/3iZvST7",CA: "https://amzn.to/37QZD3p",UK: ""},
	B086Q2M7FK: {US: "https://amzn.to/2CyUOQN",CA: "",UK: ""},
	B07GBY2WJJ: {US: "https://amzn.to/2VxdCGN",CA: "https://amzn.to/2BP7Edk",UK: ""},
	B07SFJXLYW: {US: "https://amzn.to/3fEkMAO",CA: "https://amzn.to/2WKcAb5 ",UK: ""},
	B07Q19RL7D: {US: "https://amzn.to/2DGB8uO",CA: "https://amzn.to/2XEHuCo",UK: ""},
	B00QBZ2BX2: {US: "https://amzn.to/30bZHaj",CA: "https://amzn.to/3dIvLbm",UK: ""},
	B012H0KA5A: {US: "https://amzn.to/3gYAI1b",CA: "https://amzn.to/3hArcCr",UK: ""},
	B00EYN1NEG: {US: "https://amzn.to/2Zr2Zax",CA: "https://amzn.to/30bTDjY",UK: ""},
	B00CEMH3C0: {US: "https://amzn.to/2PgMckX",CA: "",UK: ""},
	B07PDXKSGJ: {US: "https://amzn.to/2PfRRrr",CA: "",UK: ""},
	B07NRBDMJR: {US: "https://amzn.to/30rh2hb",CA: "",UK: ""},
	B085797ZFF: {US: "https://amzn.to/3gzuV24",CA: "",UK: ""},
	B0867GMW9X: {US: "https://amzn.to/2PiitYJ",CA: "",UK: ""},
	B07S76WBGF: {US: "https://amzn.to/3fpnOrQ",CA: "",UK: ""},
	B07CHYKRK7: {US: "https://amzn.to/3flxEep",CA: "",UK: ""},
	B01N9P4NH5: {US: "https://amzn.to/2XwbZKj",CA: "",UK: ""}
	}
	return dataAMZ;
}
